name: Flutter - Build App Bundle on PR Merge to Main

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "github.event.pull_request.merged == true"
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12.x

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.0.5

      - name: Install dependencies
        run: flutter pub get 

      - name: Build release APK  
        run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
          
      - name: Build App Bundle
        run: flutter build appbundle --release
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/bundle/release/app-release.aab
